# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: booking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"\x1f\n\rBookingUserId\x12\x0e\n\x06userid\x18\x01 \x01(\t\"7\n\x0b\x42ookingData\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x18\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\t.DateData\"0\n\x08\x44\x61teData\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x16\n\x06movies\x18\x02 \x03(\x0b\x32\x06.Movie\"\x16\n\x05Movie\x12\r\n\x05movie\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2l\n\x07\x42ooking\x12\x34\n\x12GetBookingByUserID\x12\x0e.BookingUserId\x1a\x0c.BookingData\"\x00\x12+\n\x0fGetListBookings\x12\x06.Empty\x1a\x0c.BookingData\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BOOKINGUSERID']._serialized_start=17
  _globals['_BOOKINGUSERID']._serialized_end=48
  _globals['_BOOKINGDATA']._serialized_start=50
  _globals['_BOOKINGDATA']._serialized_end=105
  _globals['_DATEDATA']._serialized_start=107
  _globals['_DATEDATA']._serialized_end=155
  _globals['_MOVIE']._serialized_start=157
  _globals['_MOVIE']._serialized_end=179
  _globals['_EMPTY']._serialized_start=181
  _globals['_EMPTY']._serialized_end=188
  _globals['_BOOKING']._serialized_start=190
  _globals['_BOOKING']._serialized_end=298
# @@protoc_insertion_point(module_scope)
