openapi: 3.1.0
info:
  title: Movies Endpoints
  version: 1.0.0

paths:
  /movies:
    get:
      summary: Get all movies
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schema/Movie'

  /movies/{id}:
    get:
      summary: Get a movie by id
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
          description: Movie id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schema/Movie'
        '404':
          description: Not Found
    delete:
      summary: Delete a movie by id
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
          description: Movie id
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
    patch:
      summary: Update a movie rating
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
          description: Movie id
          requestBody:
            description: Movie rating
            required: true
            content:
                application/json:
                schema:
                    type: object
                    properties:
                    rating:
                        type: number
                        format: float
                        minimum: 0
                        maximum: 10
                        exclusiveMaximum: true
      responses:
        '204':
          description: Movie rating updated
        '404':
          description: Not Found

  /actors/{id}:
    get:
      summary: Get an actor by id
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
          description: Actor id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schema/Actor'
        '404':
          description: Not Found


components:
  schema:
    Actor:
        type: object
        properties:
          id:
            type: string
            format: uuid
          firstName:
            type: string
          lastName:
            type: string
          birthyear:
            type: integer
            format: int32
          films:
            type: array
            items:
              $ref: '#/components/schema/Movie'
    Movie:
        type: object
        properties:
          id:
            type: string
            format: uuid
          title:
            type: string
          director:
            type: string
          rating:
            type: number
            format: float
          actors:
            type: array
            items:
                $ref: '#/components/schema/Actor'




