# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: showtime.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshowtime.proto\"\x0f\n\rEmptyShowTime\"\x1c\n\x0cShowtimeDate\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"\x1e\n\rShowtimeMovie\x12\r\n\x05movie\x18\x01 \x01(\t\"9\n\x0cShowtimeData\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x1b\n\x06movies\x18\x02 \x03(\x0b\x32\x0b.Movie_list\"\x1b\n\nMovie_list\x12\r\n\x05movie\x18\x01 \x01(\t\"\x1e\n\rShowtimeDates\x12\r\n\x05\x64\x61tes\x18\x01 \x03(\t2\xae\x01\n\x08Showtime\x12\x35\n\x10GetListShowtimes\x12\x0e.EmptyShowTime\x1a\r.ShowtimeData\"\x00\x30\x01\x12\x33\n\x11GetShowtimeByDate\x12\r.ShowtimeDate\x1a\r.ShowtimeData\"\x00\x12\x36\n\x12GetShowtimeByMovie\x12\x0e.ShowtimeMovie\x1a\x0e.ShowtimeDates\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'showtime_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EMPTYSHOWTIME']._serialized_start=18
  _globals['_EMPTYSHOWTIME']._serialized_end=33
  _globals['_SHOWTIMEDATE']._serialized_start=35
  _globals['_SHOWTIMEDATE']._serialized_end=63
  _globals['_SHOWTIMEMOVIE']._serialized_start=65
  _globals['_SHOWTIMEMOVIE']._serialized_end=95
  _globals['_SHOWTIMEDATA']._serialized_start=97
  _globals['_SHOWTIMEDATA']._serialized_end=154
  _globals['_MOVIE_LIST']._serialized_start=156
  _globals['_MOVIE_LIST']._serialized_end=183
  _globals['_SHOWTIMEDATES']._serialized_start=185
  _globals['_SHOWTIMEDATES']._serialized_end=215
  _globals['_SHOWTIME']._serialized_start=218
  _globals['_SHOWTIME']._serialized_end=392
# @@protoc_insertion_point(module_scope)
